# Generated by Django 5.2.9 on 2026-02-04 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Name of the person on the certificate', max_length=255)),
                ('parent_guardian', models.CharField(blank=True, help_text='Required for child dedications', max_length=255, null=True)),
                ('phone_number', models.CharField(help_text='Format: +2547XXXXXXXX', max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('certificate_type', models.CharField(choices=[('BAPTISM', 'Baptism'), ('DEDICATION', 'Child Dedication')], max_length=20)),
                ('ceremony_date', models.DateField()),
                ('is_picked_up', models.BooleanField(default=False, verbose_name='Has been picked up?')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('last_reminder_sent', models.DateTimeField(blank=True, null=True)),
                ('reminder_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-ceremony_date'],
            },
        ),
    ]
