# Generated by Django 5.2.9 on 2026-02-04 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Baptism',
            fields=[
            ],
            options={
                'verbose_name': 'Baptism Certificate',
                'verbose_name_plural': 'Baptism Certificates',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('certificates.certificate',),
        ),
        migrations.CreateModel(
            name='Dedication',
            fields=[
            ],
            options={
                'verbose_name': 'Child Dedication',
                'verbose_name_plural': 'Child Dedications',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('certificates.certificate',),
        ),
        migrations.AlterModelOptions(
            name='certificate',
            options={},
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='last_reminder_sent',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='reminder_count',
        ),
        migrations.AddField(
            model_name='certificate',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='officiating_pastor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name="Name / Child's Name"),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='is_picked_up',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='parent_guardian',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
    ]
