# Generated by Django 5.2.9 on 2026-02-05 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0002_baptism_dedication_alter_certificate_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HolyCommunion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('participants_count', models.PositiveIntegerField(verbose_name='Total Participants')),
                ('sheet_image', models.ImageField(help_text='Upload a photo of the attendance sheet', upload_to='communion_sheets/')),
            ],
            options={
                'verbose_name': 'Holy Communion Record',
                'ordering': ['-date'],
            },
        ),
        migrations.AlterField(
            model_name='certificate',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
    ]
