# Generated by Django 5.2.9 on 2026-02-05 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0003_holycommunion_alter_certificate_full_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('transfer_type', models.CharField(choices=[('IN', 'Incoming'), ('OUT', 'Outgoing')], default='IN', max_length=3)),
                ('church_involved', models.CharField(help_text='SDA Church transferring to/from', max_length=255)),
                ('stage', models.CharField(choices=[('PR', 'Processing'), ('R1', 'First Reading'), ('R2', 'Second Reading'), ('MB', 'Member (Finalized)')], default='PR', max_length=2)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('date_started', models.DateField(auto_now_add=True)),
                ('last_updated', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Membership Transfer',
                'ordering': ['-last_updated'],
            },
        ),
    ]
