# Generated by Django 5.2.9 on 2026-02-05 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0004_membertransfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='membertransfer',
            name='date_completed',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
    ]
